spring.datasource.url=jdbc:postgresql://localhost:5432/raizesdonordes
spring.datasource.username=postgres
spring.datasource.password=190928

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true